language: python
python:
  - "3.5"

sudo: required
dist: trusty

cache:
  apt: false
  directories:
    - $HOME/.cache/pip
    - $HOME/lib

script:
  - wget ftp://ftp.wwpdb.org/pub/pdb/data/structures/divided/pdb/ni/pdb2nip.ent.gz
